#####################################################
#
# 项目名称: lsky-upload
# 项目地址: https://github.com/YGXB-net/lsky-upload
# 项目文档及教程: https://github.com/YGXB-net/lsky-upload/doc
#
#####################################################

# 此文件为 lsky-upload 的配置文件，请正确填写此文件后再运行程序

# Lsky 服务器地址
# 例如： https://example.com
lsky-server:

# Lsky 接口Token
# 例如：1|2kDE7QCXRhIWfgXC9bF3axSbCr1dBjIfRPebQ2oo
lsky-auth-token:
